### ISSUE TITLE
Build fails: thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by zelenij** [tokio-rs/prost#881]
I'm sure I'm doing something wrong, but can't figure it out.

My `build.rs`:

```
use std::io::Result;

fn main() -> Result<()> {
    let mut prost_build_inst = prost_build::Config::new();

    prost_build_inst.include_file("_includes.rs");
    prost_build_inst.compile_protos(
        &[
            "src/proto/common.proto",
            "src/proto/some-data.proto",
            "src/proto/other-data.proto"
        ],
        &["src/proto"]
    )?;
    Ok(())
}
```

Inclusion point in the `lib.rs`:

```
extern crate core;

include!(concat!(env!("OUT_DIR"), "/_includes.rs"));

pub mod settings;
[...]
```

Error message:

```
  --- stderr
  thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/andre/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-build-0.11.9/src/lib.rs:1343:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
     1: core::panicking::panic_fmt
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
     2: core::panicking::panic_bounds_check
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:162:5
     3: <usize as core::slice::index::SliceIndex<[T]>>::index
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/index.rs:261:10
     4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/index.rs:19:9
     5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/vec/mod.rs:2691:9
     6: prost_build::Module::part
     7: prost_build::Config::write_includes
     8: prost_build::Config::compile_fds
     9: prost_build::Config::compile_protos
    10: build_script_build::main
    11: core::ops::function::FnOnce::call_once
```

**Comment by zelenij** [comment]
Right, it turns out that one of my `.proto` files had no package declaration. Somehow this caused the generated `_includes.rs` file to be empty.  I don't think having no package is invalid pe se, but once I added it, the problem resolved.  I can understand why having no package name in proto might not work well with the generated include file. Maybe this particular scenario can be detected by prost and reported as a more meaningful error?

**Comment by LucioFranco** [comment]
@zelenij we could probably add a nice error message.
